/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConfirmRouteImport } from './routes/api/confirm'
import { Route as ApiProactiveRouteImport } from './routes/api/proactive'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmRoute = ApiConfirmRouteImport.update({
  id: '/api/confirm',
  path: '/api/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProactiveRoute = ApiProactiveRouteImport.update({
  id: '/api/proactive',
  path: '/api/proactive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/confirm': typeof ApiConfirmRoute
  '/api/proactive': typeof ApiProactiveRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/confirm': typeof ApiConfirmRoute
  '/api/proactive': typeof ApiProactiveRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/confirm': typeof ApiConfirmRoute
  '/api/proactive': typeof ApiProactiveRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/confirm' | '/api/proactive' | '/api/stream' | '/api/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/confirm' | '/api/proactive' | '/api/stream' | '/api/transcribe'
  id:
    | '__root__'
    | '/'
    | '/api/confirm'
    | '/api/proactive'
    | '/api/stream'
    | '/api/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfirmRoute: typeof ApiConfirmRoute
  ApiProactiveRoute: typeof ApiProactiveRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm': {
      id: '/api/confirm'
      path: '/api/confirm'
      fullPath: '/api/confirm'
      preLoaderRoute: typeof ApiConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proactive': {
      id: '/api/proactive'
      path: '/api/proactive'
      fullPath: '/api/proactive'
      preLoaderRoute: typeof ApiProactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfirmRoute: ApiConfirmRoute,
  ApiProactiveRoute: ApiProactiveRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
